// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package dbStruct

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type questionsTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *questionsTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("questions").
func (v *questionsTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *questionsTableType) Columns() []string {
	return []string{"id", "question", "true_answer", "fk_ticket"}
}

// NewStruct makes a new struct for that view or table.
func (v *questionsTableType) NewStruct() reform.Struct {
	return new(Questions)
}

// NewRecord makes a new record for that table.
func (v *questionsTableType) NewRecord() reform.Record {
	return new(Questions)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *questionsTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// QuestionsTable represents questions view or table in SQL database.
var QuestionsTable = &questionsTableType{
	s: parse.StructInfo{Type: "Questions", SQLSchema: "", SQLName: "questions", Fields: []parse.FieldInfo{{Name: "ID", Type: "int32", Column: "id"}, {Name: "Question", Type: "string", Column: "question"}, {Name: "TrueAnswer", Type: "string", Column: "true_answer"}, {Name: "FkTicket", Type: "int32", Column: "fk_ticket"}}, PKFieldIndex: 0},
	z: new(Questions).Values(),
}

// String returns a string representation of this struct or record.
func (s Questions) String() string {
	res := make([]string, 4)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Question: " + reform.Inspect(s.Question, true)
	res[2] = "TrueAnswer: " + reform.Inspect(s.TrueAnswer, true)
	res[3] = "FkTicket: " + reform.Inspect(s.FkTicket, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Questions) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Question,
		s.TrueAnswer,
		s.FkTicket,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Questions) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Question,
		&s.TrueAnswer,
		&s.FkTicket,
	}
}

// View returns View object for that struct.
func (s *Questions) View() reform.View {
	return QuestionsTable
}

// Table returns Table object for that record.
func (s *Questions) Table() reform.Table {
	return QuestionsTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Questions) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Questions) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Questions) HasPK() bool {
	return s.ID != QuestionsTable.z[QuestionsTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *Questions) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int32(i64)
	} else {
		s.ID = pk.(int32)
	}
}

// check interfaces
var (
	_ reform.View   = QuestionsTable
	_ reform.Struct = (*Questions)(nil)
	_ reform.Table  = QuestionsTable
	_ reform.Record = (*Questions)(nil)
	_ fmt.Stringer  = (*Questions)(nil)
)

func init() {
	parse.AssertUpToDate(&QuestionsTable.s, new(Questions))
}
