// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package dbStruct

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type studentGroupsTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *studentGroupsTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("student_groups").
func (v *studentGroupsTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *studentGroupsTableType) Columns() []string {
	return []string{"id", "group_name", "fk_speciality"}
}

// NewStruct makes a new struct for that view or table.
func (v *studentGroupsTableType) NewStruct() reform.Struct {
	return new(StudentGroups)
}

// NewRecord makes a new record for that table.
func (v *studentGroupsTableType) NewRecord() reform.Record {
	return new(StudentGroups)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *studentGroupsTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// StudentGroupsTable represents student_groups view or table in SQL database.
var StudentGroupsTable = &studentGroupsTableType{
	s: parse.StructInfo{Type: "StudentGroups", SQLSchema: "", SQLName: "student_groups", Fields: []parse.FieldInfo{{Name: "ID", Type: "int32", Column: "id"}, {Name: "GroupName", Type: "string", Column: "group_name"}, {Name: "FkSpeciality", Type: "int32", Column: "fk_speciality"}}, PKFieldIndex: 0},
	z: new(StudentGroups).Values(),
}

// String returns a string representation of this struct or record.
func (s StudentGroups) String() string {
	res := make([]string, 3)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "GroupName: " + reform.Inspect(s.GroupName, true)
	res[2] = "FkSpeciality: " + reform.Inspect(s.FkSpeciality, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *StudentGroups) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.GroupName,
		s.FkSpeciality,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *StudentGroups) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.GroupName,
		&s.FkSpeciality,
	}
}

// View returns View object for that struct.
func (s *StudentGroups) View() reform.View {
	return StudentGroupsTable
}

// Table returns Table object for that record.
func (s *StudentGroups) Table() reform.Table {
	return StudentGroupsTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *StudentGroups) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *StudentGroups) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *StudentGroups) HasPK() bool {
	return s.ID != StudentGroupsTable.z[StudentGroupsTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *StudentGroups) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int32(i64)
	} else {
		s.ID = pk.(int32)
	}
}

// check interfaces
var (
	_ reform.View   = StudentGroupsTable
	_ reform.Struct = (*StudentGroups)(nil)
	_ reform.Table  = StudentGroupsTable
	_ reform.Record = (*StudentGroups)(nil)
	_ fmt.Stringer  = (*StudentGroups)(nil)
)

func init() {
	parse.AssertUpToDate(&StudentGroupsTable.s, new(StudentGroups))
}
