// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package dbStruct

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type userAnswersTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *userAnswersTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("user_answers").
func (v *userAnswersTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *userAnswersTableType) Columns() []string {
	return []string{"id", "answer", "fk_question"}
}

// NewStruct makes a new struct for that view or table.
func (v *userAnswersTableType) NewStruct() reform.Struct {
	return new(UserAnswers)
}

// NewRecord makes a new record for that table.
func (v *userAnswersTableType) NewRecord() reform.Record {
	return new(UserAnswers)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *userAnswersTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// UserAnswersTable represents user_answers view or table in SQL database.
var UserAnswersTable = &userAnswersTableType{
	s: parse.StructInfo{Type: "UserAnswers", SQLSchema: "", SQLName: "user_answers", Fields: []parse.FieldInfo{{Name: "ID", Type: "int32", Column: "id"}, {Name: "Answer", Type: "string", Column: "answer"}, {Name: "FkQuestion", Type: "int32", Column: "fk_question"}}, PKFieldIndex: 0},
	z: new(UserAnswers).Values(),
}

// String returns a string representation of this struct or record.
func (s UserAnswers) String() string {
	res := make([]string, 3)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Answer: " + reform.Inspect(s.Answer, true)
	res[2] = "FkQuestion: " + reform.Inspect(s.FkQuestion, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *UserAnswers) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Answer,
		s.FkQuestion,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *UserAnswers) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Answer,
		&s.FkQuestion,
	}
}

// View returns View object for that struct.
func (s *UserAnswers) View() reform.View {
	return UserAnswersTable
}

// Table returns Table object for that record.
func (s *UserAnswers) Table() reform.Table {
	return UserAnswersTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *UserAnswers) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *UserAnswers) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *UserAnswers) HasPK() bool {
	return s.ID != UserAnswersTable.z[UserAnswersTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *UserAnswers) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int32(i64)
	} else {
		s.ID = pk.(int32)
	}
}

// check interfaces
var (
	_ reform.View   = UserAnswersTable
	_ reform.Struct = (*UserAnswers)(nil)
	_ reform.Table  = UserAnswersTable
	_ reform.Record = (*UserAnswers)(nil)
	_ fmt.Stringer  = (*UserAnswers)(nil)
)

func init() {
	parse.AssertUpToDate(&UserAnswersTable.s, new(UserAnswers))
}
