// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package dbStruct

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type subjectsTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *subjectsTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("subjects").
func (v *subjectsTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *subjectsTableType) Columns() []string {
	return []string{"id", "subject_name"}
}

// NewStruct makes a new struct for that view or table.
func (v *subjectsTableType) NewStruct() reform.Struct {
	return new(Subjects)
}

// NewRecord makes a new record for that table.
func (v *subjectsTableType) NewRecord() reform.Record {
	return new(Subjects)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *subjectsTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// SubjectsTable represents subjects view or table in SQL database.
var SubjectsTable = &subjectsTableType{
	s: parse.StructInfo{Type: "Subjects", SQLSchema: "", SQLName: "subjects", Fields: []parse.FieldInfo{{Name: "ID", Type: "int32", Column: "id"}, {Name: "SubjectName", Type: "string", Column: "subject_name"}}, PKFieldIndex: 0},
	z: new(Subjects).Values(),
}

// String returns a string representation of this struct or record.
func (s Subjects) String() string {
	res := make([]string, 2)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "SubjectName: " + reform.Inspect(s.SubjectName, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Subjects) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.SubjectName,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Subjects) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.SubjectName,
	}
}

// View returns View object for that struct.
func (s *Subjects) View() reform.View {
	return SubjectsTable
}

// Table returns Table object for that record.
func (s *Subjects) Table() reform.Table {
	return SubjectsTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Subjects) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Subjects) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Subjects) HasPK() bool {
	return s.ID != SubjectsTable.z[SubjectsTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *Subjects) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int32(i64)
	} else {
		s.ID = pk.(int32)
	}
}

// check interfaces
var (
	_ reform.View   = SubjectsTable
	_ reform.Struct = (*Subjects)(nil)
	_ reform.Table  = SubjectsTable
	_ reform.Record = (*Subjects)(nil)
	_ fmt.Stringer  = (*Subjects)(nil)
)

func init() {
	parse.AssertUpToDate(&SubjectsTable.s, new(Subjects))
}
