// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package dbStruct

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type testUsersSubjectTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *testUsersSubjectTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("test_users_subject").
func (v *testUsersSubjectTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *testUsersSubjectTableType) Columns() []string {
	return []string{"id", "fk_test_users", "fk_subject"}
}

// NewStruct makes a new struct for that view or table.
func (v *testUsersSubjectTableType) NewStruct() reform.Struct {
	return new(TestUsersSubject)
}

// NewRecord makes a new record for that table.
func (v *testUsersSubjectTableType) NewRecord() reform.Record {
	return new(TestUsersSubject)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *testUsersSubjectTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// TestUsersSubjectTable represents test_users_subject view or table in SQL database.
var TestUsersSubjectTable = &testUsersSubjectTableType{
	s: parse.StructInfo{Type: "TestUsersSubject", SQLSchema: "", SQLName: "test_users_subject", Fields: []parse.FieldInfo{{Name: "ID", Type: "int32", Column: "id"}, {Name: "FkTestUsers", Type: "int32", Column: "fk_test_users"}, {Name: "FkSubject", Type: "int32", Column: "fk_subject"}}, PKFieldIndex: 0},
	z: new(TestUsersSubject).Values(),
}

// String returns a string representation of this struct or record.
func (s TestUsersSubject) String() string {
	res := make([]string, 3)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "FkTestUsers: " + reform.Inspect(s.FkTestUsers, true)
	res[2] = "FkSubject: " + reform.Inspect(s.FkSubject, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *TestUsersSubject) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.FkTestUsers,
		s.FkSubject,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *TestUsersSubject) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.FkTestUsers,
		&s.FkSubject,
	}
}

// View returns View object for that struct.
func (s *TestUsersSubject) View() reform.View {
	return TestUsersSubjectTable
}

// Table returns Table object for that record.
func (s *TestUsersSubject) Table() reform.Table {
	return TestUsersSubjectTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *TestUsersSubject) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *TestUsersSubject) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *TestUsersSubject) HasPK() bool {
	return s.ID != TestUsersSubjectTable.z[TestUsersSubjectTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *TestUsersSubject) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int32(i64)
	} else {
		s.ID = pk.(int32)
	}
}

// check interfaces
var (
	_ reform.View   = TestUsersSubjectTable
	_ reform.Struct = (*TestUsersSubject)(nil)
	_ reform.Table  = TestUsersSubjectTable
	_ reform.Record = (*TestUsersSubject)(nil)
	_ fmt.Stringer  = (*TestUsersSubject)(nil)
)

func init() {
	parse.AssertUpToDate(&TestUsersSubjectTable.s, new(TestUsersSubject))
}
